---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kantetask-codereliant-io-v1-entrytask
  failurePolicy: Fail
  name: ventrytask.kb.io
  rules:
  - apiGroups:
    - kantetask.codereliant.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - entrytasks
  sideEffects: None
