apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
    - name: https
      nodePort: 30900
      port: 9090
      protocol: TCP
      targetPort: 8443
  selector:
    prometheus: prometheus
