---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - services
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - kantetask.codereliant.io
  resources:
  - entrytasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kantetask.codereliant.io
  resources:
  - entrytasks/finalizers
  verbs:
  - update
- apiGroups:
  - kantetask.codereliant.io
  resources:
  - entrytasks/status
  verbs:
  - get
  - patch
  - update
