apiVersion: kantetask.codereliant.io/v1
kind: EntryTask
metadata:
  labels:
    app.kubernetes.io/name: entrytask-operator
    app.kubernetes.io/managed-by: kustomize
  name: entrytask-sample
spec:
  # TODO(user): Add fields here
  desired_replicas: 3
  image: nginx:1.14.2
  selector:
    matchLabels:
      app: entrytask
  template:
    metadata:
      labels:
        app: entrytask
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80

