apiVersion: kantetask.codereliant.io/v1
kind: EntryTask
metadata:
  labels:
    app.kubernetes.io/name: entrytask-operator
    app.kubernetes.io/managed-by: kustomize
  name: entrytask-sample
spec:
  # TODO(user): Add fields here
